// Code generated by MockGen. DO NOT EDIT.
// Source: requests.go

// Package mock_serv is a generated GoMock package.
package mock_serv

import (
	reflect "reflect"

	requests "github.com/IDL13/balance_ms/internal/requests"
	gomock "github.com/golang/mock/gomock"
)

// MockRequest is a mock of Request interface.
type MockRequest struct {
	ctrl     *gomock.Controller
	recorder *MockRequestMockRecorder
}

// MockRequestMockRecorder is the mock recorder for MockRequest.
type MockRequestMockRecorder struct {
	mock *MockRequest
}

// NewMockRequest creates a new mock instance.
func NewMockRequest(ctrl *gomock.Controller) *MockRequest {
	mock := &MockRequest{ctrl: ctrl}
	mock.recorder = &MockRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequest) EXPECT() *MockRequestMockRecorder {
	return m.recorder
}

// AddBalanceRequest mocks base method.
func (m *MockRequest) AddBalanceRequest(id int64, balance string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBalanceRequest", id, balance)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBalanceRequest indicates an expected call of AddBalanceRequest.
func (mr *MockRequestMockRecorder) AddBalanceRequest(id, balance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBalanceRequest", reflect.TypeOf((*MockRequest)(nil).AddBalanceRequest), id, balance)
}

// AddReserveRequest mocks base method.
func (m *MockRequest) AddReserveRequest(id int64, idService, idOrder, money string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReserveRequest", id, idService, idOrder, money)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReserveRequest indicates an expected call of AddReserveRequest.
func (mr *MockRequestMockRecorder) AddReserveRequest(id, idService, idOrder, money interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReserveRequest", reflect.TypeOf((*MockRequest)(nil).AddReserveRequest), id, idService, idOrder, money)
}

// GetBalanceRequest mocks base method.
func (m *MockRequest) GetBalanceRequest(id int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceRequest", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceRequest indicates an expected call of GetBalanceRequest.
func (mr *MockRequestMockRecorder) GetBalanceRequest(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceRequest", reflect.TypeOf((*MockRequest)(nil).GetBalanceRequest), id)
}

// GetReserveRequest mocks base method.
func (m *MockRequest) GetReserveRequest() ([]requests.DataStruct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReserveRequest")
	ret0, _ := ret[0].([]requests.DataStruct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReserveRequest indicates an expected call of GetReserveRequest.
func (mr *MockRequestMockRecorder) GetReserveRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReserveRequest", reflect.TypeOf((*MockRequest)(nil).GetReserveRequest))
}
