// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewReserve struct {
	IDUser    string `json:"idUser"`
	IDService string `json:"IdService"`
	IDOrder   string `json:"IdOrder"`
	Money     string `json:"money"`
}

type NewUser struct {
	ID      string `json:"id"`
	Balance string `json:"balance"`
}

type Reserve struct {
	IDUser    string `json:"idUser"`
	IDService string `json:"IdService"`
	IDOrder   string `json:"IdOrder"`
	Money     string `json:"money"`
}

type User struct {
	ID      string `json:"id"`
	Balance string `json:"balance"`
}
